# This function will prevent in-source builds
function(AssertOutOfSourceBuild)
    # make sure the user doesn't play dirty with symlinks
    get_filename_component(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
    get_filename_component(bindir "${CMAKE_BINARY_DIR}" REALPATH)

    if("${srcdir}" STREQUAL "${bindir}")
        message("##########################################################################################")
        message("# ${PROJECT_NAME} should not be configured & built in the ${PROJECT_NAME} source directory")
        message("# You must run cmake in a build directory.")
        message("# For example:")
        message("#     git clone ssh://git@stash.cert.qbase.us:45022/project.git ${PROJECT_NAME}")
        message("#     cd ${PROJECT_NAME}/build")
        message("#")
        message("# Then you may proceed to configure and build")
        message("# by using the following commands")
        message("#")
        message("# For Windows - NMake files")
        message("#     cmake -G \"NMake Makefiles\" -DCMAKE_BUILD_TYPE=Debug ..")
        message("#     nmake")
        message("#")
        message("# For Windows - Visual Studio")
        message("#     cmake -G \"Visual Studio 12 Win64\" ..")
        message("#     Open the Visual Studio solution file")
        message("#")
        message("# For Linux - Make files")
        message("#     cmake -G \"Unix Makefiles\" -DCMAKE_BUILD_TYPE=Debug ..")
        message("#     make -j4")
        message("#")
        message("# NOTE: Given that you already tried to make an in-source build")
        message("#       CMake has already created several files & directories")
        message("#       in your source tree. run 'git status' to find them and")
        message("#       remove them by doing:")
        message("#")
        message("#       git clean -n -d")
        message("#       git clean -f -d")
        message("#       git checkout --")
        message("#")
        message("##########################################################################################")
        message(FATAL_ERROR "Terminating configuration")
    endif()
endfunction()

AssertOutOfSourceBuild()
