get_filename_component(_self_dir "${CMAKE_CURRENT_LIST_FILE}" PATH)

set(LIBRARY_NAME_DEBUG_POSTFIX          "")
set(LIBRARY_NAME_RELEASE_POSTFIX        "")
set(LIBRARY_NAME_RELWITHDEBINFO_POSTFIX "")

set(OUTPUT_PATH_DEBUG           "Debug")
set(OUTPUT_PATH_RELEASE         "Release")
set(OUTPUT_PATH_RELWITHDEBINFO  "RelWithDebInfo")

if(CMAKE_BUILD_TOOL MATCHES MSBuild)
    set(LIBRARY_DIRS_HINT ${LIBRARY_OUTPUT_PATH}/$(ConfigurationName))
else()
    set(LIBRARY_DIRS_HINT ${LIBRARY_OUTPUT_PATH}/${CMAKE_BUILD_TYPE})
endif()

string(REGEX REPLACE "/W[2-4]" "/W1" CZMQ_CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
set(CZMQ_CMAKE_CXX_FLAGS "${CZMQ_CMAKE_CXX_FLAGS} -DZMQ_STATIC")
set(CZMQ_CMAKE_CXX_FLAGS "${CZMQ_CMAKE_CXX_FLAGS} -DLIBCZMQ_STATIC")

ExternalProject_Add("${CZMQ_PROJECT}"
  DEPENDS "${ZEROMQ_PROJECT}"
  GIT_REPOSITORY "${czmq_git_repository}"
  GIT_TAG "${czmq_git_tag}"
  INSTALL_COMMAND ""
  BUILD_IN_SOURCE 0
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL="${BUILD_SHARED_LIBS}"
    -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}"
    -DCMAKE_CXX_FLAGS=${CZMQ_CMAKE_CXX_FLAGS}
    -DCMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}
    -DCMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}
    -DCMAKE_CXX_FLAGS_RELWITHDEBINFO=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}
    -DLIBRARY_OUTPUT_PATH:PATH=${LIBRARY_DIRS_HINT}
    -DEXECUTABLE_OUTPUT_PATH:PATH=${EXECUTABLE_OUTPUT_PATH}
    -DPC_ZEROMQ_INCLUDE_DIRS=${ZEROMQ_INCLUDES}
    -DPC_ZEROMQ_LIBRARY_DIRS=${LIBRARY_DIRS_HINT}
  )

if (DEBUG_CMAKE)
    message("")
    message(STATUS "Start Debug - ${CZMQ_PROJECT}")
    message(STATUS "  CMAKE_ARGS")
    message(STATUS "    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}")
    message(STATUS "    -DDEBUG_CMAKE:BOOL=ON")
    message(STATUS "    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
    message(STATUS "    -DCMAKE_CXX_FLAGS=${MEMDB_CMAKE_CXX_FLAGS}")
    message(STATUS "    -DCMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}")
    message(STATUS "    -DCMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}")
    message(STATUS "    -DCMAKE_CXX_FLAGS_RELWITHDEBINFO=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
    message(STATUS "    -DLIBRARY_OUTPUT_PATH:PATH=${LIBRARY_OUTPUT_PATH}")
    message(STATUS "    -DEXECUTABLE_OUTPUT_PATH:PATH=${LIBRARY_DIRS_HINT}")
    message(STATUS "    -DPC_ZEROMQ_INCLUDE_DIRS=${ZEROMQ_INCLUDES}")
    message(STATUS "    -DPC_ZEROMQ_LIBRARY_DIRS=${LIBRARY_DIRS_HINT}/($ConfigurationName)")
    message(STATUS "End Debug - ${CZMQ_PROJECT} - CMAKE_ARGS")
    message("")
endif()

set_target_properties("${CZMQ_PROJECT}" PROPERTIES FOLDER "External Libraries" )
  
#
# Specify include directory
#
ExternalProject_Get_Property("${CZMQ_PROJECT}" SOURCE_DIR)
set(czmq_include_dir ${SOURCE_DIR}/include CACHE STRING "Include directory for ${czmq_library}.")
set(CZMQ_INCLUDE_DIR ${czmq_include_dir} CACHE STRING "Include directories for ${czmq_library}.")
set(CZMQ_INCLUDES    ${czmq_include_dir} ${ZEROMQ_INCLUDES} CACHE STRING "Include directories for ${czmq_library}, including prerequisite libraries.")

#
# Specify the library
#
ExternalProject_Get_Property("${CZMQ_PROJECT}" BINARY_DIR)
set(CZMQ_LIBRARY_PATH_DEBUG          "${CMAKE_BINARY_DIR}/${LIB_OUTPUT_DIRECTORY}/${OUTPUT_PATH_DEBUG}")
set(CZMQ_LIBRARY_PATH_RELEASE        "${CMAKE_BINARY_DIR}/${LIB_OUTPUT_DIRECTORY}/${OUTPUT_PATH_RELEASE}")
set(CZMQ_LIBRARY_PATH_RELWITHDEBINFO "${CMAKE_BINARY_DIR}/${LIB_OUTPUT_DIRECTORY}/${OUTPUT_PATH_RELWITHDEBINFO}")
set(CZMQ_LIBRARY_DEBUG               "${CMAKE_FIND_LIBRARY_PREFIXES}${CZMQ_PROJECT}${LIBRARY_NAME_DEBUG_POSTFIX}")
set(CZMQ_LIBRARY_RELEASE             "${CMAKE_FIND_LIBRARY_PREFIXES}${CZMQ_PROJECT}${LIBRARY_NAME_RELEASE_POSTFIX}")
set(CZMQ_LIBRARY_RELWITHDEBINFO      "${CMAKE_FIND_LIBRARY_PREFIXES}${CZMQ_PROJECT}${LIBRARY_NAME_RELWITHDEBINFO_POSTFIX}")

# add the libraries to global scope and per configuration location to be linked
add_library(CZMQ_LIBRARIES STATIC IMPORTED GLOBAL)
set_target_properties(CZMQ_LIBRARIES PROPERTIES IMPORTED_LOCATION_DEBUG          "${CZMQ_LIBRARY_PATH_DEBUG}/${CZMQ_LIBRARY_DEBUG}${CMAKE_STATIC_LIBRARY_SUFFIX}")
set_target_properties(CZMQ_LIBRARIES PROPERTIES IMPORTED_LOCATION_RELEASE        "${CZMQ_LIBRARY_PATH_RELEASE}/${CZMQ_LIBRARY_RELEASE}${CMAKE_STATIC_LIBRARY_SUFFIX}")
set_target_properties(CZMQ_LIBRARIES PROPERTIES IMPORTED_LOCATION_RELWITHDEBINFO "${CZMQ_LIBRARY_PATH_RELWITHDEBINFO}/${CZMQ_LIBRARY_RELWITHDEBINFO}${CMAKE_STATIC_LIBRARY_SUFFIX}")

#add dependency so any project which includes library will automatically make CZMQ_PROJECT a dependency
add_dependencies(CZMQ_LIBRARIES "${CZMQ_PROJECT}")

if (DEBUG_CMAKE)
    message("CZMQ_INCLUDE_DIR   - ${CZMQ_INCLUDE_DIR}")
    message("CZMQ_INCLUDES      - ${CZMQ_INCLUDES}")
    message("CZMQ_LIBRARIES     - ${CZMQ_LIBRARIES}")
    message("  DEBUG            - ${CZMQ_LIBRARY_PATH_DEBUG}/${CZMQ_LIBRARY_DEBUG}${CMAKE_STATIC_LIBRARY_SUFFIX}")
    message("  RELEASE          - ${CZMQ_LIBRARY_PATH_RELEASE}/${CZMQ_LIBRARY_RELEASE}${CMAKE_STATIC_LIBRARY_SUFFIX}")
    message("  RELWITHDEBINFO   - ${CZMQ_LIBRARY_PATH_RELWITHDEBINFO}/${CZMQ_LIBRARY_RELWITHDEBINFO}${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif()
